In [2]:
import numpy as np

In [3]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]], dtype=np.float32)
b = np.array([[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16,17], [18,19,20,21,22,23]], dtype=np.float32)
c = np.zeros((4, 6), dtype=np.float32)
print(a,b,c)
for i in range(100000):
    c += a @ b

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]] [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
print(c)
print(a @ b)

[[ 8400000.  9000000.  9600000. 10200000. 10800000. 11400000.]
 [22800000. 25000000. 27200000. 29400000. 31600000. 33798552.]
 [37200000. 40963680. 44800000. 48661912. 52400000. 56119416.]
 [51600000. 56917736. 62400000. 67901016. 73233280. 78485384.]]
[[ 84.  90.  96. 102. 108. 114.]
 [228. 250. 272. 294. 316. 338.]
 [372. 410. 448. 486. 524. 562.]
 [516. 570. 624. 678. 732. 786.]]


In [11]:
a = np.arange(48*48, dtype=np.float32).reshape(48, 48, order='F')
b = np.arange(48*48, dtype=np.float32).reshape(48, 48, order='F')
c = np.zeros((48, 48), dtype=np.float32, order='F')

In [14]:
d = a @ b

In [18]:
d[1][8]

22525412.0

In [19]:
d[8][1]

4340928.0

In [17]:
np.set_printoptions(threshold=np.inf)
print(d)

[[1.71456000e+06 4.31347200e+06 6.91238400e+06 9.51129600e+06
  1.21102080e+07 1.47091200e+07 1.73080320e+07 1.99069440e+07
  2.25058560e+07 2.51047680e+07 2.77036800e+07 3.03025920e+07
  3.29015040e+07 3.55004160e+07 3.80993280e+07 4.06982400e+07
  4.32971520e+07 4.58960640e+07 4.84949760e+07 5.10938880e+07
  5.36928000e+07 5.62917120e+07 5.88906240e+07 6.14895360e+07
  6.40884480e+07 6.66873600e+07 6.92862720e+07 7.18851840e+07
  7.44840960e+07 7.70830080e+07 7.96819200e+07 8.22808320e+07
  8.48797440e+07 8.74786560e+07 9.00775680e+07 9.26764800e+07
  9.52753920e+07 9.78743040e+07 1.00473216e+08 1.03072128e+08
  1.05671040e+08 1.08269952e+08 1.10868864e+08 1.13467776e+08
  1.16066688e+08 1.18665600e+08 1.21264512e+08 1.23863424e+08]
 [1.71568800e+06 4.31690400e+06 6.91812000e+06 9.51933600e+06
  1.21205520e+07 1.47217680e+07 1.73229840e+07 1.99242000e+07
  2.25254120e+07 2.51266280e+07 2.77278440e+07 3.03290600e+07
  3.29302760e+07 3.55314880e+07 3.81327040e+07 4.07339200e+07
  4.333