In [1]:
import numpy as np

In [13]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]], dtype=np.float32)
b = np.array([[0,1,2,3,4,5], [6,7,8,9,10,11], [12,13,14,15,16,17], [18,19,20,21,22,23]], dtype=np.float32)
c = np.zeros((4, 6), dtype=np.float32)
print(a,b,c)
for i in range(100000):
    c += a @ b

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]] [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
print(c)
print(a @ b)

[[ 8400000.  9000000.  9600000. 10200000. 10800000. 11400000.]
 [22800000. 25000000. 27200000. 29400000. 31600000. 33798552.]
 [37200000. 40963680. 44800000. 48661912. 52400000. 56119416.]
 [51600000. 56917736. 62400000. 67901016. 73233280. 78485384.]]
[[ 84.  90.  96. 102. 108. 114.]
 [228. 250. 272. 294. 316. 338.]
 [372. 410. 448. 486. 524. 562.]
 [516. 570. 624. 678. 732. 786.]]
